/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-122031-gc4d22f2d2c-20251208"
#endif /* AVUTIL_FFVERSION_H */
